begin;
create temporary table experience_results(name text,passed boolean);
grant insert,select on experience_results to authenticated,anon;
select set_config('test.client',(select id::text from public.profiles where role='client' order by id limit 1),true);
select set_config('test.other',(select id::text from public.profiles where role='client' order by id offset 1 limit 1),true);
select set_config('test.admin',(select id::text from public.profiles where role='admin' limit 1),true);
select set_config('test.project',gen_random_uuid()::text,true);
select set_config('test.quote',gen_random_uuid()::text,true);
select set_config('test.delivery',gen_random_uuid()::text,true);
select set_config('test.review',gen_random_uuid()::text,true);
-- Disposable fixture only. No email is dispatched inside this rolled-back transaction.
insert into public.projects(id,user_id,title,service_type,brief) values(current_setting('test.project')::uuid,current_setting('test.client')::uuid,'Experience rollback fixture','Business Website','Verification without actual payments or sending emails');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
update public.projects set preview_url='https://example.com/preview',revision_bonus=0 where id=current_setting('test.project')::uuid;
insert into public.project_quotes(id,project_id,created_by,title,scope,base_amount,discount_percent,revisions,delivery_date) values(current_setting('test.quote')::uuid,current_setting('test.project')::uuid,auth.uid(),'Agreed website','Five pages and responsive design',160,10,1,current_date+14);
insert into public.project_reviews(id,project_id,created_by,title,preview_url) values(current_setting('test.review')::uuid,current_setting('test.project')::uuid,auth.uid(),'Homepage design','https://example.com/preview');
insert into public.project_deliveries(id,project_id,created_by,title,instructions) values(current_setting('test.delivery')::uuid,current_setting('test.project')::uuid,auth.uid(),'Initial delivery','Review the final files');
insert into public.project_handover(project_id,maintenance_name,maintenance_scope,maintenance_amount,maintenance_status) values(current_setting('test.project')::uuid,'Care plan','Updates and monthly checks',25,'offered');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
update public.project_quotes set status='accepted',decided_at=now()+interval '1 year' where id=current_setting('test.quote')::uuid;
insert into experience_results select 'proposal stores price, date and server decision time',amount=144 and delivery_date=current_date+14 and decided_at=now() from public.project_quotes where id=current_setting('test.quote')::uuid;
update public.project_reviews set status='changes_requested',feedback='Please move the navigation and change the heading.',decided_at=now() where id=current_setting('test.review')::uuid;
insert into experience_results select 'design changes consume one included round automatically',count(*)=1 and bool_and(counts_allowance) from public.project_revision_requests where project_id=current_setting('test.project')::uuid;
insert into public.delivery_decisions(project_id,delivery_id,client_id,decision,feedback) values(current_setting('test.project')::uuid,current_setting('test.delivery')::uuid,auth.uid(),'changes_requested','Please update the final contact details and footer.');
insert into experience_results select 'delivery changes beyond allowance require extra quote',count(*)=1 and bool_and(status='extra_quote' and not counts_allowance) from public.project_revision_requests where delivery_id=current_setting('test.delivery')::uuid;
insert into public.maintenance_requests(project_id,client_id) values(current_setting('test.project')::uuid,auth.uid());
insert into experience_results select 'maintenance request snapshots offered price and scope',plan_name='Care plan' and amount=25 and plan_scope='Updates and monthly checks' and status='requested' from public.maintenance_requests where project_id=current_setting('test.project')::uuid;
insert into public.portal_onboarding(user_id) values(auth.uid()) on conflict(user_id) do update set completed_at=now();
insert into experience_results select 'onboarding saved to own account',exists(select 1 from public.portal_onboarding where user_id=auth.uid());
update public.portal_notifications set read_at=now() where project_id=current_setting('test.project')::uuid;
insert into experience_results select 'client can mark own notifications read',count(*)>=3 and bool_and(read_at=now()) from public.portal_notifications where project_id=current_setting('test.project')::uuid;
do $$declare n int;begin
 begin update public.projects set status='cancelled',revision_bonus=99 where id=current_setting('test.project')::uuid;insert into experience_results values('client cannot grant revision rounds',false);exception when others then insert into experience_results values('client cannot grant revision rounds',true);end;
 begin insert into public.portal_notifications(recipient_id,project_id,event_key,kind,label,tab) values(auth.uid(),current_setting('test.project')::uuid,'forged','payments','Fake payment','payments');insert into experience_results values('client cannot forge notifications',false);exception when insufficient_privilege then insert into experience_results values('client cannot forge notifications',true);end;
 begin update public.delivery_decisions set decision='accepted' where project_id=current_setting('test.project')::uuid;insert into experience_results values('delivery decision is immutable',false);exception when insufficient_privilege then insert into experience_results values('delivery decision is immutable',true);end;
 update public.project_revision_requests set status='completed' where project_id=current_setting('test.project')::uuid;get diagnostics n=row_count;insert into experience_results values('client cannot handle own revision request',n=0);
 begin insert into public.portal_onboarding(user_id) values(current_setting('test.admin')::uuid);insert into experience_results values('client cannot write another onboarding record',false);exception when insufficient_privilege then insert into experience_results values('client cannot write another onboarding record',true);end;
end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.other'),'role','authenticated')::text,true);
set local role authenticated;
insert into experience_results select 'another client cannot read private workflows',not exists(select 1 from public.project_revision_requests where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.delivery_decisions where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.maintenance_requests where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.portal_notifications where project_id=current_setting('test.project')::uuid);
do $$begin
 begin insert into public.delivery_decisions(project_id,delivery_id,client_id,decision) values(current_setting('test.project')::uuid,current_setting('test.delivery')::uuid,auth.uid(),'accepted');insert into experience_results values('another client cannot decide delivery',false);exception when others then insert into experience_results values('another client cannot decide delivery',true);end;
end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
insert into experience_results select 'admin receives client decision notifications',exists(select 1 from public.portal_notifications where project_id=current_setting('test.project')::uuid and label='Delivery: changes requested' and recipient_id=auth.uid());
do $$begin
 begin update public.project_revision_requests set status='in_progress' where project_id=current_setting('test.project')::uuid and status='extra_quote';insert into experience_results values('extra work cannot start without additional allowance',false);exception when others then insert into experience_results values('extra work cannot start without additional allowance',sqlerrm='Grant an extra revision round before starting this request');end;
end;$$;
update public.projects set revision_bonus=1 where id=current_setting('test.project')::uuid;
update public.project_revision_requests set status='in_progress',response='Changes are in progress.' where project_id=current_setting('test.project')::uuid and status='extra_quote';
insert into experience_results select 'admin grants extra round and handles request',count(*)=1 and bool_and(counts_allowance) from public.project_revision_requests where project_id=current_setting('test.project')::uuid and status='in_progress';
update public.maintenance_requests set status='active' where project_id=current_setting('test.project')::uuid;
update public.project_handover set maintenance_status='active',renewal_date=current_date+5 where project_id=current_setting('test.project')::uuid;
insert into public.project_deliveries(project_id,created_by,title,instructions,created_at) values(current_setting('test.project')::uuid,auth.uid(),'Updated final delivery','All requested changes included',now()+interval '1 second');
reset role;
select renobva_private.maintenance_reminders();select renobva_private.maintenance_reminders();
insert into experience_results select 'renewal reminder is deduplicated for client and admin',count(*)=2 from public.portal_notifications where project_id=current_setting('test.project')::uuid and event_key like 'renewal:%';
select set_config('test.final_delivery',(select id::text from public.project_deliveries where project_id=current_setting('test.project')::uuid order by created_at desc,id desc limit 1),true);
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.delivery_decisions(project_id,delivery_id,client_id,decision) values(current_setting('test.project')::uuid,current_setting('test.final_delivery')::uuid,auth.uid(),'accepted');
insert into experience_results select 'client accepts latest delivery with recorded decision',exists(select 1 from public.delivery_decisions where delivery_id=current_setting('test.final_delivery')::uuid and decision='accepted');
insert into public.project_testimonials(project_id,client_id,display_name,rating,body,consent) values(current_setting('test.project')::uuid,auth.uid(),'Test client',5,'The project was clear and easy to follow.',true);
reset role;
set local role anon;
insert into experience_results select 'unapproved testimonial is hidden from public',not exists(select 1 from public.project_testimonials where display_name='Test client' and body='The project was clear and easy to follow.');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
update public.project_testimonials set approved=true where project_id=current_setting('test.project')::uuid;
insert into experience_results select 'new workflow actions are in private admin history',count(*)>=6 from public.project_activity where project_id=current_setting('test.project')::uuid;
reset role;
set local role anon;
insert into experience_results select 'approved consented testimonial exposes only public fields',exists(select 1 from public.project_testimonials where display_name='Test client' and body='The project was clear and easy to follow.' and rating=5);
do $$begin
 begin perform client_id from public.project_testimonials;insert into experience_results values('public cannot read testimonial client identity',false);exception when insufficient_privilege then insert into experience_results values('public cannot read testimonial client identity',true);end;
end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
delete from public.project_testimonials where project_id=current_setting('test.project')::uuid;
insert into experience_results select 'client can withdraw a published testimonial',not exists(select 1 from public.project_testimonials where project_id=current_setting('test.project')::uuid);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
update public.projects set archived_at=now() where id=current_setting('test.project')::uuid;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
do $$begin
 begin insert into public.project_revision_requests(project_id,quote_id,requested_by,title,body) values(current_setting('test.project')::uuid,current_setting('test.quote')::uuid,auth.uid(),'Archived changes','This should not be saved on an archived project.');insert into experience_results values('archived project blocks new revisions',false);exception when others then insert into experience_results values('archived project blocks new revisions',true);end;
end;$$;
reset role;
select * from experience_results;
rollback;
