const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/assets/js/modules/project-usability-core.js'),'utf8'),context);const u=context.window.RENOBVA_USABILITY;
test('Trash and archived projects stay out of current queues',()=>{assert.equal(u.visible({deleted_at:'2026-01-01'},'all'),false);assert.equal(u.visible({archived_at:'2026-01-01'},'current'),false);assert.equal(u.visible({archived_at:'2026-01-01'},'archived'),true);assert.equal(u.visible({archived_at:'2026-01-01',deleted_at:'2026-02-01'},'archived'),false);assert.equal(u.visible({deleted_at:'2026-01-01'},'trash'),true);});
test('Lifecycle distinguishes restore targets',()=>{assert.equal(u.lifecycle({}),'current');assert.equal(u.lifecycle({archived_at:'date'}),'archived');assert.equal(u.lifecycle({deleted_at:'date'}),'trash');});
test('Only incoming unread messages contribute to the badge',()=>{const messages=[{sender_id:'other',created_at:'2026-01-01T10:00:00Z'},{sender_id:'me',created_at:'2026-01-01T12:00:00Z'},{sender_id:'other',created_at:'2026-01-01T13:00:00Z'},{sender_id:'other',created_at:'2026-01-01T14:00:00Z',deleted_at:'date'},{sender_id:'other',created_at:'2026-01-01T15:00:00Z',body:'Project brief attachment'}];assert.equal(u.unread(messages,'me','2026-01-01T11:00:00Z'),1);assert.equal(u.unread(messages,'me',null),2);});
test('Clients cannot select the admin activity tab',()=>{assert.equal(u.selectedTab('activity',false),'overview');assert.equal(u.selectedTab('activity',true),'activity');assert.equal(u.selectedTab('invalid',true),'overview');assert.equal(u.selectedTab('chat',false),'chat');});
test('Draft snapshots exclude passwords, files, hidden totals and disabled inputs',()=>{const form={elements:[{name:'scope',type:'textarea',value:'A five page website'},{name:'password',type:'password',value:'do-not-save'},{name:'file',type:'file',value:'private'},{name:'amount',type:'hidden',value:'144'},{name:'disabled',type:'text',disabled:true,value:'old'},{name:'agree',type:'checkbox',checked:true}]};const values=u.fields(form);assert.equal(values.scope,'A five page website');assert.equal(values.agree,true);assert.deepEqual(Object.keys(values).sort(),['agree','scope']);});
function checkout(project){let serve,stripeCalls=0;const query=table=>({select(){return this},eq(){return this},single:async()=>({data:table==='projects'?project:{id:'payment',project_id:'project',client_id:'client',status:'pending',amount:144,currency:'EUR',title:'Discounted project'}})});const c={createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'client'}}})},from:query}),Deno:{serve:fn=>serve=fn,env:{get:()=>undefined}},Response,URL,URLSearchParams,JSON,fetch:async()=>{stripeCalls++;},console};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../supabase/functions/stripe-checkout/index.js'),'utf8').replace(/^import.*\n/,''),c);return {run:()=>serve(new Request('https://example.com',{method:'POST',headers:{Authorization:'Bearer user-token'},body:JSON.stringify({payment_id:'payment'})})),calls:()=>stripeCalls};}
test('Archived and trashed projects cannot start Stripe checkout',async()=>{for(const p of [{archived_at:'date'},{deleted_at:'date'}]){const w=checkout(p);assert.equal((await w.run()).status,409);assert.equal(w.calls(),0);}});
