begin;
create temporary table usability_results(name text,passed boolean);
grant insert,select on usability_results to authenticated;
select set_config('test.client',(select id::text from public.profiles where role='client' order by id limit 1),true);
select set_config('test.other',(select id::text from public.profiles where role='client' order by id offset 1 limit 1),true);
select set_config('test.admin',(select id::text from public.profiles where role='admin' limit 1),true);
select set_config('test.project',gen_random_uuid()::text,true);
select set_config('test.quote',gen_random_uuid()::text,true);
select set_config('test.review',gen_random_uuid()::text,true);
select set_config('test.payment',gen_random_uuid()::text,true);
select set_config('test.message',gen_random_uuid()::text,true);
-- Project creation normally goes through the existing verified-email Edge Function. Create only this disposable fixture as postgres.
insert into public.projects(id,user_id,title,service_type,brief) values(current_setting('test.project')::uuid,current_setting('test.client')::uuid,'Usability rollback fixture','Business Website','Testing the full project workflow without sending emails or taking payment.');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.project_quotes(id,project_id,created_by,title,scope,base_amount,discount_percent) values(current_setting('test.quote')::uuid,current_setting('test.project')::uuid,current_setting('test.admin')::uuid,'Website quote','Five pages and responsive layouts',160,10);
insert into public.project_reviews(id,project_id,created_by,title,preview_url) values(current_setting('test.review')::uuid,current_setting('test.project')::uuid,current_setting('test.admin')::uuid,'Homepage review','https://example.com');
insert into public.payment_requests(id,project_id,client_id,created_by,title,amount,note) values(current_setting('test.payment')::uuid,current_setting('test.project')::uuid,current_setting('test.client')::uuid,current_setting('test.admin')::uuid,'Agreed discounted website',144,'10% off EUR160');
insert into public.messages(id,project_id,sender_id,body,created_at) values(current_setting('test.message')::uuid,current_setting('test.project')::uuid,current_setting('test.admin')::uuid,'Please review your design.',now()-interval '1 minute');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
update public.project_quotes set status='accepted',decided_at=now() where id=current_setting('test.quote')::uuid;
update public.project_reviews set status='approved',decided_at=now() where id=current_setting('test.review')::uuid;
select public.submit_payment_request(current_setting('test.payment')::uuid,'bank','rollback-test');
select public.mark_project_read(current_setting('test.project')::uuid,current_setting('test.message')::uuid);
insert into usability_results select 'client accepts quote, approves review and submits bank payment',exists(select 1 from public.project_quotes where id=current_setting('test.quote')::uuid and amount=144 and status='accepted') and exists(select 1 from public.project_reviews where id=current_setting('test.review')::uuid and status='approved') and exists(select 1 from public.payment_requests where id=current_setting('test.payment')::uuid and status='submitted');
insert into usability_results select 'read receipt stores the viewed message cutoff',exists(select 1 from public.project_read_receipts r join public.messages m on m.project_id=r.project_id and m.created_at=r.last_read_at where m.id=current_setting('test.message')::uuid and r.user_id=auth.uid());
insert into usability_results select 'client cannot see admin activity',not exists(select 1 from public.project_activity where project_id=current_setting('test.project')::uuid);
do $$begin
 begin update public.projects set archived_at=now() where id=current_setting('test.project')::uuid;exception when others then null;end;insert into usability_results select 'client cannot archive a project',archived_at is null from public.projects where id=current_setting('test.project')::uuid;
 begin insert into public.project_read_receipts(project_id,user_id,last_read_at) values(current_setting('test.project')::uuid,current_setting('test.admin')::uuid,now()-interval '1 minute');insert into usability_results values('client cannot forge admin read receipt',false);exception when insufficient_privilege then insert into usability_results values('client cannot forge admin read receipt',true);end;
end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
update public.payment_requests set status='paid',paid_at=now() where id=current_setting('test.payment')::uuid;
insert into usability_results select 'payment confirmation creates an immutable document',exists(select 1 from public.payment_documents where payment_id=current_setting('test.payment')::uuid and amount=144);
insert into public.project_deliveries(project_id,created_by,title,instructions,preview_url) values(current_setting('test.project')::uuid,current_setting('test.admin')::uuid,'Finished website','Your final instructions','https://example.com');
update public.projects set status='completed',archived_at=now() where id=current_setting('test.project')::uuid;
insert into usability_results select 'admin can read client receipt',exists(select 1 from public.project_read_receipts where project_id=current_setting('test.project')::uuid and user_id=current_setting('test.client')::uuid);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
insert into usability_results select 'archived project remains visible to its client',exists(select 1 from public.projects where id=current_setting('test.project')::uuid and archived_at is not null);
do $$begin
 begin insert into public.messages(project_id,sender_id,body) values(current_setting('test.project')::uuid,auth.uid(),'Must be rejected');insert into usability_results values('archived chat is read-only',false);exception when insufficient_privilege then insert into usability_results values('archived chat is read-only',true);end;
 begin insert into public.workspace_files(project_id,uploaded_by,category,attachment_path,attachment_name,attachment_size) values(current_setting('test.project')::uuid,auth.uid(),'Content',current_setting('test.project')||'/library/test.txt','test.txt',100);insert into usability_results values('archived file uploads are rejected',false);exception when insufficient_privilege then insert into usability_results values('archived file uploads are rejected',true);end;
end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
update public.projects set deleted_at=now() where id=current_setting('test.project')::uuid;
insert into usability_results select 'activity records quotes, approvals, payment and archive/trash changes',count(*)>=8 from public.project_activity where project_id=current_setting('test.project')::uuid;
do $$begin begin delete from public.projects where id=current_setting('test.project')::uuid;insert into usability_results values('issued payment documents prevent permanent project deletion',false);exception when others then insert into usability_results values('issued payment documents prevent permanent project deletion',sqlerrm='Issued payment documents must be retained. Restore or archive this project.');end;end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
insert into usability_results select 'Trash is hidden from client projects and chat',not exists(select 1 from public.projects where id=current_setting('test.project')::uuid) and not exists(select 1 from public.messages where project_id=current_setting('test.project')::uuid);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
update public.projects set deleted_at=null,archived_at=null where id=current_setting('test.project')::uuid;
insert into usability_results select 'restoration retains the project conversation',exists(select 1 from public.messages where id=current_setting('test.message')::uuid) and exists(select 1 from public.projects where id=current_setting('test.project')::uuid and deleted_at is null and archived_at is null);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.other'),'role','authenticated')::text,true);
set local role authenticated;
insert into usability_results select 'other client cannot see conversation receipts',not exists(select 1 from public.project_read_receipts where project_id=current_setting('test.project')::uuid);
reset role;

select set_config('test.disposable',gen_random_uuid()::text,true);
insert into public.projects(id,user_id,title,service_type,brief) values(current_setting('test.disposable')::uuid,current_setting('test.client')::uuid,'Disposable trash fixture','Business Website','Rollback-only deletion verification');
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.project_milestones(project_id,title) values(current_setting('test.disposable')::uuid,'Disposable milestone');
insert into public.payment_requests(project_id,client_id,created_by,title,amount,stripe_locked) values(current_setting('test.disposable')::uuid,current_setting('test.client')::uuid,current_setting('test.admin')::uuid,'Active checkout fixture',10,true);
update public.projects set deleted_at=now() where id=current_setting('test.disposable')::uuid;
do $$begin begin delete from public.projects where id=current_setting('test.disposable')::uuid;insert into usability_results values('active checkout prevents permanent deletion',false);exception when others then insert into usability_results values('active checkout prevents permanent deletion',sqlerrm='A Stripe checkout is active. Resolve it before permanently deleting this project.');end;end;$$;
reset role;
-- Simulate a signed Stripe cancellation callback using the service/database role.
select set_config('request.jwt.claims','{"role":"service_role"}',true);
update public.payment_requests set status='cancelled' where project_id=current_setting('test.disposable')::uuid;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
delete from public.projects where id=current_setting('test.disposable')::uuid;
insert into usability_results select 'unpaid trashed project can be permanently deleted with child cascade',not exists(select 1 from public.projects where id=current_setting('test.disposable')::uuid) and not exists(select 1 from public.project_milestones where project_id=current_setting('test.disposable')::uuid);
reset role;
select * from usability_results;
rollback;
