begin;
create temporary table workspace_test_results(name text,passed boolean);
grant select,insert on workspace_test_results to authenticated;
select set_config('test.client',(select id::text from public.profiles where role='client' order by id limit 1),true);
select set_config('test.other_client',(select id::text from public.profiles where role='client' order by id offset 1 limit 1),true);
select set_config('test.admin',(select id::text from public.profiles where role='admin' limit 1),true);
select set_config('test.project',gen_random_uuid()::text,true);
insert into public.projects(id,user_id,title,service_type,brief) values(current_setting('test.project')::uuid,current_setting('test.client')::uuid,'Workspace verification fixture','Business Website','Temporary rollback-only verification');
insert into public.notification_preferences(user_id,email) values(current_setting('test.client')::uuid,true) on conflict(user_id) do update set email=true;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.admin'),'role','authenticated')::text,true);
set local role authenticated;
select public.apply_project_template(current_setting('test.project')::uuid,(select id from public.project_templates where title='Business website' limit 1));
insert into workspace_test_results select 'admin applies template atomically',count(*)=5 from public.project_milestones where project_id=current_setting('test.project')::uuid;
insert into public.project_handover(project_id,website_url,instructions) values(current_setting('test.project')::uuid,'https://example.com','Test handover');
insert into public.messages(project_id,sender_id,body) values(current_setting('test.project')::uuid,current_setting('test.admin')::uuid,'Test notification, rollback only');
insert into workspace_test_results select 'opted in email is queued',count(*)=1 from public.workspace_email_queue where project_id=current_setting('test.project')::uuid and kind='messages';
insert into public.payment_requests(project_id,client_id,created_by,title,amount,status,note) values(current_setting('test.project')::uuid,current_setting('test.client')::uuid,current_setting('test.admin')::uuid,'Discounted test payment',144,'paid','10% off EUR160');
insert into workspace_test_results select 'confirmed payment creates one receipt at stored amount',count(*)=1 and min(amount)=144 and min(document_type)='receipt' from public.payment_documents where project_id=current_setting('test.project')::uuid;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.client'),'role','authenticated')::text,true);
set local role authenticated;
insert into workspace_test_results select 'client can see own milestones',count(*)=5 from public.project_milestones where project_id=current_setting('test.project')::uuid;
insert into workspace_test_results select 'private tasks hidden from client',count(*)=0 from public.project_tasks where project_id=current_setting('test.project')::uuid;
insert into public.workspace_files(project_id,uploaded_by,category,attachment_path,attachment_name,attachment_size) values(current_setting('test.project')::uuid,current_setting('test.client')::uuid,'Logos',current_setting('test.project')||'/library/test.png','test.png',100);
insert into public.project_comments(project_id,author_id,page_url,section,body) values(current_setting('test.project')::uuid,current_setting('test.client')::uuid,'https://example.com','Hero','Please change this heading.');
insert into workspace_test_results select 'client creates feedback and file metadata',exists(select 1 from public.project_comments where project_id=current_setting('test.project')::uuid) and exists(select 1 from public.workspace_files where project_id=current_setting('test.project')::uuid);
do $$declare n int;begin
 update public.project_milestones set status='completed' where project_id=current_setting('test.project')::uuid;get diagnostics n=row_count;insert into workspace_test_results values('client cannot change milestones',n=0);
 begin update public.payment_documents set amount=1 where project_id=current_setting('test.project')::uuid;insert into workspace_test_results values('client cannot alter invoice amount',false);exception when insufficient_privilege then insert into workspace_test_results values('client cannot alter invoice amount',true);end;
 begin perform public.apply_project_template(current_setting('test.project')::uuid,gen_random_uuid());insert into workspace_test_results values('client cannot apply admin template',false);exception when others then insert into workspace_test_results values('client cannot apply admin template',sqlerrm='Admin access required');end;
end;$$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.other_client'),'role','authenticated')::text,true);
set local role authenticated;
insert into workspace_test_results select 'another client cannot see project workspace',not exists(select 1 from public.project_milestones where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.workspace_files where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.project_comments where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.project_handover where project_id=current_setting('test.project')::uuid) and not exists(select 1 from public.payment_documents where project_id=current_setting('test.project')::uuid);
reset role;
select * from workspace_test_results;
rollback;
