const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const source=name=>fs.readFileSync(path.join(__dirname,'../',name),'utf8');
test('workspace helpers escape HTML and reject unsafe preview links',()=>{const context={window:{},Intl,URL};vm.runInNewContext(source('public/assets/js/modules/workspace-tools.js'),context);const t=context.window.RENOBVA_TOOLS;assert.equal(t.escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');assert.throws(()=>t.https('javascript:alert(1)'));assert.throws(()=>t.https('http://example.com'));assert.equal(t.https('https://example.com'),'https://example.com/');assert.match(t.money(144),/144/);});
function worker({authorized=true,configured=true,pref=true,providerStatus=200}={}){
 let handler,claimed=0,sends=0,patches=[];const job={id:'job-1',project_id:'project-1',recipient_id:'client-1',kind:'messages',label:'New project message',created_at:new Date().toISOString(),attempts:1};
 const sb={rpc:async name=>name==='authorize_workspace_mail_worker'?{data:authorized}:{data:(claimed++,[job])},from:table=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:table==='notification_preferences'?{email:pref,messages:true}:table==='projects'?{title:'Test project',user_id:'client-1'}:{role:'client'}}),update(patch){patches.push(patch);return this},then(resolve){resolve({error:null})}}),auth:{admin:{getUserById:async()=>({data:{user:{id:'client-1',email:'example@example.com',email_confirmed_at:'verified'}}})}}};
 const context={Deno:{env:{get:key=>['RESEND_API_KEY','EMAIL_FROM'].includes(key)&&!configured?undefined:key==='SITE_URL'?'https://example.com':'test'},serve:f=>handler=f},createClient:()=>sb,Response,Date,AbortSignal,JSON,fetch:async()=>{sends++;return {ok:providerStatus===200,status:providerStatus,json:async()=>({id:'provider-1'})}}};
 const code=source('supabase/functions/workspace-notifications/index.js').replace(/^import.*\n/,'');vm.runInNewContext(code,context);
 return {run:token=>handler(new Request('https://example.com',{method:'POST',headers:{Authorization:'Bearer '+(token||'x'.repeat(72))}})),get state(){return {claimed,sends,patches}}};
}
test('email worker rejects unauthorized requests without claiming or sending',async()=>{const w=worker({authorized:false});assert.equal((await w.run()).status,401);assert.equal(w.state.claimed,0);assert.equal(w.state.sends,0);});
test('short authentication tokens never reach the worker authorization RPC',async()=>{const w=worker();assert.equal((await w.run('bad')).status,401);assert.equal(w.state.claimed,0);});
test('missing email configuration leaves the queue untouched',async()=>{const w=worker({configured:false});assert.equal((await w.run()).status,200);assert.equal(w.state.claimed,0);assert.equal(w.state.sends,0);});
test('email opt-out skips delivery',async()=>{const w=worker({pref:false});await w.run();assert.equal(w.state.sends,0);assert.equal(w.state.patches[0].status,'skipped');});
test('verified opted-in client receives one email and durable delivery status',async()=>{const w=worker();const response=await w.run();assert.equal((await response.json()).sent,1);assert.equal(w.state.sends,1);assert.equal(w.state.patches[0].status,'sent');});
test('provider failure schedules retry without marking the update delivered',async()=>{const w=worker({providerStatus:429});await w.run();assert.equal(w.state.patches[0].status,'pending');assert.match(w.state.patches[0].last_error,/429/);assert.ok(Date.parse(w.state.patches[0].next_attempt_at)>Date.now());});
